"""
SQL Execution Service
Safely executes read-only queries generated by the SQL Agent
"""
from models import db
from sqlalchemy import text
from decimal import Decimal
from datetime import date, datetime, time

class SQLExecutor:
    """
    Executes raw SQL queries ensuring read-only access and binding parameters.
    """
    
    @staticmethod
    def execute_query(sql_query: str, params: dict) -> dict:
        """
        Execute SQL query with permission validation and bound parameters.
        Supports multiple statements separated by semicolon.
        """
        import logging
        import time

        # Configure logger
        logger = logging.getLogger("SQLExecutor")
        if not logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
            handler.setFormatter(formatter)
            logger.addHandler(handler)
            logger.setLevel(logging.INFO)

        # 1. Clean and split logic
        # Remove comments line by line
        lines = [line for line in sql_query.splitlines() if not line.strip().startswith('--')]
        clean_sql = "\n".join(lines).strip()
        
        # Split into statements
        statements = [s.strip() for s in clean_sql.split(';') if s.strip()]
        
        if not statements:
             logger.warning("No executable SQL statements found.")
             return {"success": False, "error": "No executable SQL statements found (all comments?)."}
             
        allowed_actions = params.get('allowed_actions', ['select'])
        
        # Block dangerous schema operations broadly
        forbidden_keywords = ["drop ", "alter ", "truncate ", "create ", "grant ", "revoke "]
        if any(kw in clean_sql.lower() for kw in forbidden_keywords):
             logger.error("SECURITY ALERT: Forbidden schema modification attempted.")
             return {"success": False, "error": "SECURITY: Schema modifications are strictly forbidden."}

        # Results accumulator
        combined_results = []
        total_rows_affected = 0
        
        start_time = time.time()
        
        try:
            for statement in statements:
                # Permission Check per statement
                query_word = statement.split()[0].lower()
                
                # Treat WITH (CTEs) as SELECT for permission checking
                effective_action = 'select' if query_word == 'with' else query_word
                
                if effective_action not in allowed_actions:
                    logger.warning(f"SECURITY: Unauthorized action '{query_word}' rejected.")
                    return {
                        "success": False,
                        "error": f"SECURITY: Action '{query_word.upper()}' is not allowed for your role (Effective: {effective_action})."
                    }
                
                # Execute
                if effective_action == 'select':
                    result = db.session.execute(text(statement), params)
                    rows = [dict(row._mapping) for row in result]
                    
                    # Tag results if multiple queries
                    serialized = SQLExecutor._serialize_rows(rows)
                    if len(statements) > 1:
                        combined_results.extend(serialized) 
                    else:
                        combined_results = serialized
                        
                else:
                    # Write operations
                    result = db.session.execute(text(statement), params)
                    total_rows_affected += result.rowcount
            
            # Commit writes if any
            if total_rows_affected > 0:
                db.session.commit()
                elapsed = time.time() - start_time
                logger.info(f"✅ Write Success. Rows affected: {total_rows_affected}. Time: {elapsed:.2f}s")
                return {
                    "success": True,
                    "count": total_rows_affected,
                    "data": f"Success. Total rows affected: {total_rows_affected}"
                }
            
            # Return read results
            elapsed = time.time() - start_time
            logger.info(f"✅ Read Success. Rows fetched: {len(combined_results)}. Time: {elapsed:.2f}s")
            return {
                "success": True,
                "count": len(combined_results),
                "data": combined_results
            }
            
        except Exception as e:
            # Check for MySQL Gone Away (OperationalError 2006)
            is_gone_away = '2006' in str(e) or 'Gone away' in str(e) or 'Lost connection' in str(e)
            
            if is_gone_away:
                logger.warning(f"⚠️ Connection lost ({str(e)}). Initiating RETRY logic...")
                try:
                    db.session.remove() # Force clear pool
                    # Optional: Explicit ping query check
                    try:
                         # Use a fresh engine connection just to check validity if needed, 
                         # but db.session.execute should grab a fresh one from pool.
                         pass
                    except:
                         pass

                    # Logic block repeated for Retry 1
                    combined_results_retry = []
                    total_rows_retry = 0
                    
                    for statement_retry in statements:
                        q_word = statement_retry.split()[0].lower()
                        # Re-check permissions (redundant but safe)
                        eff_act = 'select' if q_word == 'with' else q_word
                        
                        if eff_act == 'select':
                            res = db.session.execute(text(statement_retry), params)
                            rows = [dict(r._mapping) for r in res]
                            if len(statements) > 1:
                                combined_results_retry.extend(SQLExecutor._serialize_rows(rows))
                            else:
                                combined_results_retry = SQLExecutor._serialize_rows(rows)
                        else:
                            res = db.session.execute(text(statement_retry), params)
                            total_rows_retry += res.rowcount
                            
                    if total_rows_retry > 0:
                        db.session.commit()
                        logger.info("✅ Retry Write Success.")
                        return {"success": True, "count": total_rows_retry, "data": f"Success (Retry). Rows: {total_rows_retry}"}
                        
                    logger.info("✅ Retry Read Success.")
                    return {"success": True, "count": len(combined_results_retry), "data": combined_results_retry}
                    
                except Exception as retry_e:
                    db.session.rollback()
                    # Determine if it was another connection error or SQL syntax error
                    is_syntax = 'You have an error in your SQL syntax' in str(retry_e) or 'ambiguous' in str(retry_e)
                    error_type = "SQL Syntax Error" if is_syntax else "Connection Error"
                    
                    logger.error(f"❌ Retry Failed: {error_type} - {str(retry_e)}")
                    return {"success": False, "error": f"{error_type} in Retry: {str(retry_e)}"}
            
            db.session.rollback()
            logger.error(f"❌ Database Error: {str(e)}")
            return {
                "success": False,
                "error": f"Database Error: {str(e)}"
            }
            
    @staticmethod
    def _serialize_rows(rows: list) -> list:
        """Helper to convert complex types to strings for JSON"""
        cleaned = []
        for row in rows:
            formatted_row = {}
            for k, v in row.items():
                if isinstance(v, (date, datetime, time)):
                    formatted_row[k] = str(v)
                elif isinstance(v, Decimal):
                    formatted_row[k] = float(v)
                else:
                    formatted_row[k] = v
            cleaned.append(formatted_row)
        return cleaned
