'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'pt' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.product': 'Product Architecture',
    'nav.how': 'How it Works',
    'nav.traction': 'Traction',
    'nav.legal': 'Legal',
    'nav.demo': 'Request Demo',
    'nav.beta': 'Join Beta Waitlist',
    'nav.dashboard': 'Gov Dashboard',
    'nav.login': 'Sign In',

    // Hero
    'hero.eyebrow': 'Autonomous Agentic Compliance OS',
    'hero.title1': 'Turn field voice notes into ',
    'hero.titleAccent': 'audit-ready records.',
    'hero.lead': 'AI GovCoreX is the compliance infrastructure governments and public networks use to run early childhood, welfare, and social programs with zero-friction field capture and real-time regulatory visibility.',
    'hero.ctaPrimary': 'Join Beta Waitlist',
    'hero.ctaSecondary': 'See How It Works',
    'hero.trust1': 'Live in production with municipal networks',
    'hero.trust2': '11 institutional centers onboarding',
    'hero.trust3': '100% annual budget renewal rate',
    'hero.ledgerTitle': 'LIVE COMPLIANCE LEDGER',
    'hero.ledgerEngine': 'engine: langgraph-agentic-v2',
    'hero.ledgerRegion': 'region: global-cloud-01',

    // Ledger Feed Items
    'ledger.in1': '“24 children attended today, breakfast served at 10am…”',
    'ledger.out1': '{ attendance: 24, meal_served: true, time: "10:00" }',
    'ledger.status1': 'Validated against Public Health Resolution 003-2024',
    'ledger.in2': '“Center needs learning materials replenished, 3 units missing…”',
    'ledger.out2': '{ supply_request: "didactic_material", qty: 3 }',
    'ledger.status2': 'Flagged for budget reconciliation',
    'ledger.in3': '“Staff training completed, 8 educators attended…”',
    'ledger.out3': '{ training_completed: true, staff_present: 8 }',
    'ledger.status3': 'Compliance report generated',

    // Problem
    'problem.eyebrow': 'The Problem',
    'problem.title': 'Public programs are drowning in paperwork they can’t audit.',
    'problem.desc': 'Field-level reporting in social programs is still manual, fragmented, and untraceable — turning every audit season into a fire drill and every budget renewal into a gamble.',
    'problem.stat1Num': '40%',
    'problem.stat1Label': 'Operational time lost',
    'problem.stat1Sub': 'to manual bureaucracy — Public Sector Workforce Benchmark',
    'problem.stat2Num': 'Severe',
    'problem.stat2Label': 'Audit & fiscal risk',
    'problem.stat2Sub': 'Undocumented spend is the #1 reason public programs lose funding',
    'problem.stat3Num': 'Zero',
    'problem.stat3Label': 'Real-time visibility',
    'problem.stat3Sub': 'Decision-makers see program data weeks after it happens, if at all',
    'problem.impact': '~$1T / year',
    'problem.impactSub': 'Estimated global productivity opportunity from digitizing public-sector operations — McKinsey Global Institute',

    // Solution / How
    'how.eyebrow': 'The Solution',
    'how.title': 'Zero-friction voice & agentic AI compliance.',
    'how.desc': 'No new app to learn, no forms to fill. Field workers report the way they already communicate — and the system does the rest.',
    'how.step1Num': '01',
    'how.step1Title': 'Speak, don’t type',
    'how.step1Desc': 'Field workers send a voice note or message on WhatsApp or Telegram — the channels they already use daily. Zero friction.',
    'how.step2Num': '02',
    'how.step2Title': 'Agent extracts & validates',
    'how.step2Desc': 'Our LangGraph-based agentic engine structures inputs and validates them in real time against strict state regulatory frameworks.',
    'how.step3Num': '03',
    'how.step3Title': 'Compliance writes itself',
    'how.step3Desc': 'Every report becomes an audit-ready, tamper-proof record instantly visible to program directors, auditors, and government leaders.',

    // Modules
    'modules.eyebrow': 'Product Architecture',
    'modules.title': 'One compliance engine. Multiple public-sector verticals.',
    'modules.desc': 'AI GovCoreX is a horizontal RegTech OS — every specialized vertical inherits the same compliance core, audit trail, and voice-to-structure pipeline.',
    'modules.m1Tag': 'ACTIVE · BEACHHEAD',
    'modules.m1Title': 'KindiCore AI',
    'modules.m1Desc': 'Early childhood development & daycare network management. Live in production with active institutional clients.',
    'modules.m2Tag': 'NEXT VERTICAL',
    'modules.m2Title': 'SocialCore AI',
    'modules.m2Desc': 'Social welfare, mobility subsidies, and elderly care compliance. Built on the core AI GovCoreX engine.',
    'modules.m3Tag': 'ROADMAP',
    'modules.m3Title': 'HealthCore AI',
    'modules.m3Desc': 'Community health clinics, child nutrition brigades, and public health field monitoring.',

    // Traction
    'traction.eyebrow': 'Proven Execution',
    'traction.title': 'From code to institutional adoption in 5 months.',
    'traction.desc': 'Validated with active public network partners, annual budget renewals, and expanding multi-center deployments.',
    'traction.t1Tag': 'PHASE 1',
    'traction.t1Title': 'Core OS Deployed',
    'traction.t1Sub': 'Autonomous agentic engine architecture built & benchmarked.',
    'traction.t2Tag': 'PHASE 2',
    'traction.t2Title': 'Institutional Validation',
    'traction.t2Sub': 'Deployed across municipal & state-partnered centers.',
    'traction.t3Tag': 'CLIENT ANCHOR',
    'traction.t3Title': 'DASE Guayaquil',
    'traction.t3Sub': 'Budget renewed — anchor client retained in annual plan.',
    'traction.t4Tag': 'EXPANSION',
    'traction.t4Title': 'MIES Network',
    'traction.t4Sub': '11 centers onboarding under institutional agreement.',
    'traction.t5Tag': 'RETENTION',
    'traction.t5Title': '100%',
    'traction.t5Sub': 'Annual budget renewal rate to date.',

    // Moat
    'moat.eyebrow': 'Competitive Moat',
    'moat.title': 'Voice usability + real-time state compliance.',
    'moat.desc': 'No other platform bridges zero-friction field audio capture with strict, automated regulatory validation.',
    'moat.q1': 'Private Childcare CRMs (Brightwheel, Procare, Generic ERPs)',
    'moat.q2': 'AI GovCoreX (Autonomous Agentic Compliance OS)',
    'moat.q3': 'Manual Bureaucracy (Paper forms, physical binders)',
    'moat.q4': 'Legacy Public Systems (Tyler Tech, SAP Gov portals)',
    'moat.axisY': 'VOICE USABILITY & ZERO FRICTION →',
    'moat.axisX': 'REAL-TIME STATE REGULATORY COMPLIANCE →',
    'moat.m1Title': 'Proprietary domain compliance engine',
    'moat.m1Desc': 'Directly mapped against official regulatory standards, WHO guidelines, and state welfare resolutions.',
    'moat.m2Title': 'High switching costs',
    'moat.m2Desc': 'Deeply embedded inside public audit workflows, reporting lines, and annual budget allocations.',
    'moat.m3Title': 'Voice-to-audit data flywheel',
    'moat.m3Desc': 'Every field audio note refines domain extraction precision for local dialects and terminology.',

    // Footer / CTA
    'footer.ctaTitle': 'Ready to modernize public program compliance?',
    'footer.ctaDesc': 'Join governments and public program operators building the next generation of transparent, AI-driven public administration.',
    'footer.contact': 'Get in Touch',
    'footer.rights': '© 2026 AI GovCoreX. Autonomous Agentic Compliance OS for the Public Sector. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.terms': 'Terms of Service',

    // Beta Register
    'beta.header': 'Beta Access Waitlist',
    'beta.subtitle': 'Apply for exclusive access to the AI GovCoreX Beta Platform.',
    'beta.step': 'Step {{current}} of {{total}}',
    'beta.prev': 'Previous',
    'beta.next': 'Next Step',
    'beta.submit': 'Request VIP Beta Access',
    'beta.submitting': 'Submitting Application...',
    'beta.completedBadge': 'Application Received!',
    'beta.completedTitle': 'You’re on the VIP Waitlist!',
    'beta.completedSubtitle': 'We have successfully logged your application for {{company}}.',
    'beta.completedDesc': 'Our team will review your organization details and send your access credentials to {{email}}.',
    'beta.statusPending': 'Application status: Under Evaluation for Beta Onboarding',
    'beta.goToHome': 'Back to Homepage',
    'beta.q1Title': 'What is the name of your organization or government agency?',
    'beta.q1Subtitle': 'Help us understand the entity implementing AI compliance.',
    'beta.q1Placeholder': 'e.g., Department of Social Welfare / City Children Network',
    'beta.q1Badge': 'Organization Identity',

    'beta.q2Title': 'Which sector or public vertical does your entity operate in?',
    'beta.q2Subtitle': 'This allows us to tailor compliance templates and voice models.',
    'beta.q2Badge': 'Vertical Customization',
    'beta.q2Opt1': 'Early Childhood & Daycare Networks',
    'beta.q2Opt1Desc': 'Public daycares, kindergarten networks, infant welfare centers',
    'beta.q2Opt2': 'Social Assistance & Subsidies',
    'beta.q2Opt2Desc': 'Welfare distribution, vulnerability tracking, elderly care',
    'beta.q2Opt3': 'Public Health & Nutrition Brigades',
    'beta.q2Opt3Desc': 'Community health centers, vaccination & growth monitoring',
    'beta.q2Opt4': 'Education & School Administration',
    'beta.q2Opt4Desc': 'Public school districts, meal programs, educator management',
    'beta.q2Opt5': 'Municipal & Local Governance',
    'beta.q2Opt5Desc': 'City council programs, community ops, field inspections',
    'beta.q2Opt6': 'Other Public/B2G Sector',
    'beta.q2Opt6Desc': 'Other government contractors or non-profit organizations',

    'beta.q3Title': 'How many field workers or centers operate in your network?',
    'beta.q3Subtitle': 'Helps us estimate processing throughput and infrastructure capacity.',
    'beta.q3Badge': 'Scale Assessment',
    'beta.q3Opt1': '1 to 5 centers / field workers',
    'beta.q3Opt1Desc': 'Small programs or pilot networks',
    'beta.q3Opt2': '6 to 20 centers / field workers',
    'beta.q3Opt2Desc': 'Growing municipal networks',
    'beta.q3Opt3': '21 to 50 centers / field workers',
    'beta.q3Opt3Desc': 'Regional social assistance programs',
    'beta.q3Opt4': '50+ centers / field workers',
    'beta.q3Opt4Desc': 'State/National scale networks (Enterprise Gov)',

    'beta.q4Title': 'What specific programs or field reporting workflows do you run?',
    'beta.q4Subtitle': 'Briefly describe the key operational tasks your team handles daily.',
    'beta.q4Badge': 'Operational Scope',
    'beta.q4Placeholder': 'e.g., Daily child attendance logs, meal distribution tracking, weekly growth checks, field audit reports...',

    'beta.q5Title': 'What is your entity’s current level of AI adoption?',
    'beta.q5Subtitle': 'Identifies your current technological stage.',
    'beta.q5Badge': 'Digital Maturity',
    'beta.q5Opt1': 'Initial Stage / First Time',
    'beta.q5Opt1Desc': 'Occasional personal use (ChatGPT), no institutional AI integration',
    'beta.q5Opt2': 'Intermediate Stage',
    'beta.q5Opt2Desc': 'Basic automation tools, legacy forms, or simple chatbots',
    'beta.q5Opt3': 'Advanced Stage',
    'beta.q5Opt3Desc': 'Automated workflows seeking autonomous agentic AI OS',

    'beta.q6Title': 'What are your primary goals for implementing AI GovCoreX?',
    'beta.q6Subtitle': 'Your objectives will guide initial agentic pipeline configuration.',
    'beta.q6Badge': 'Key Objective',
    'beta.q6Placeholder': 'e.g., Eliminate manual paper reports, get instant audit visibility for state inspections, capture field notes via WhatsApp voice...',

    'beta.q7Title': 'Almost done! Provide your official contact details',
    'beta.q7Subtitle': 'We will send your approval and access credentials here.',
    'beta.q7Badge': 'Final Step',
    'beta.q7Name': 'Full Name',
    'beta.q7NamePh': 'e.g., Sarah Jenkins',
    'beta.q7Role': 'Official Role / Title',
    'beta.q7RolePh': 'e.g., Director of Operations / Program Coordinator',
    'beta.q7Email': 'Official Email Address',
    'beta.q7EmailPh': 'sarah@agency.gov',
    'beta.q7Phone': 'Phone / WhatsApp Number',
    'beta.q7PhonePh': '+1 (555) 019-2834',
    'beta.q7Security': 'Your information is protected with enterprise-grade SSL encryption.',

    'beta.valText': 'Please complete this field to continue.',
    'beta.valSelect': 'Please select an option to proceed.',
    'beta.valContact': 'Please complete all required contact fields.',

    // Legal pages
    'legal.termsTitle': 'Terms of Service',
    'legal.privacyTitle': 'Privacy Policy & Data Security',
    'legal.lastUpdated': 'Last updated: August 2026',
    'legal.backHome': 'Back to AI GovCoreX Home',
    'legal.privacySec1Title': '1. Data Protection & Government Compliance',
    'legal.privacySec1Text': 'AI GovCoreX employs multi-tenant database isolation, SSL encryption, and strict role-based access control (RBAC). All compliance data and field audio reports are stored in secure cloud environments compliant with state and international privacy standards.',
    'legal.privacySec2Title': '2. Usage of Collected Information',
    'legal.privacySec2Text': 'Information submitted through the Beta Waitlist registration is exclusively used for organization qualification, capacity estimation, and onboarding credentials delivery.',
    'legal.privacySec3Title': '3. Information Security',
    'legal.privacySec3Text': 'We implement administrative and technical safeguards to prevent unauthorized access, disclosure, or alteration of public program records.',
    'legal.termsSec1Title': '1. Platform Services & Governance',
    'legal.termsSec1Text': 'AI GovCoreX provides an autonomous agentic compliance operating system designed for public sector agencies, government contractors, and social welfare program administrators. By accessing or requesting beta registration, organizations agree to standard public-sector compliance protocols and data privacy guidelines.',
    'legal.termsSec2Title': '2. Voice Data & Agentic Processing',
    'legal.termsSec2Text': 'Audio field reports sent via official messaging channels (e.g. WhatsApp, Telegram) are processed using natural language extraction models strictly scoped to program regulatory frameworks. No audio data is shared with unverified third parties.',
    'legal.termsSec3Title': '3. Intellectual Property & Modular Architecture',
    'legal.termsSec3Text': 'AI GovCoreX and its vertical modules (including KindiCore AI, SocialCore AI, and HealthCore AI) remain the exclusive intellectual property of the parent entity.'
  },

  es: {
    // Nav
    'nav.product': 'Arquitectura de Producto',
    'nav.how': 'Cómo Funciona',
    'nav.traction': 'Tracción',
    'nav.legal': 'Legal',
    'nav.demo': 'Solicitar Demo',
    'nav.beta': 'Unirse a la Lista de Espera',
    'nav.dashboard': 'Panel de Gestión',
    'nav.login': 'Ingresar',

    // Hero
    'hero.eyebrow': 'Sistema Operativo Agéntico de Compliance',
    'hero.title1': 'Convierte una nota de voz en un ',
    'hero.titleAccent': 'registro listo para auditoría.',
    'hero.lead': 'AI GovCoreX es la infraestructura de cumplimiento que gobiernos y redes públicas utilizan para gestionar programas de primera infancia, asistencia social y salud con captura por voz sin fricción y visibilidad regulatoria en tiempo real.',
    'hero.ctaPrimary': 'Registrarse en Lista Beta',
    'hero.ctaSecondary': 'Ver Cómo Funciona',
    'hero.trust1': 'En producción en redes municipales',
    'hero.trust2': '11 centros institucionales en onboarding',
    'hero.trust3': '100% de renovación presupuestaria anual',
    'hero.ledgerTitle': 'LIBRO MAYOR DE COMPLIANCE EN VIVO',
    'hero.ledgerEngine': 'motor: langgraph-agentic-v2',
    'hero.ledgerRegion': 'región: nube-global-01',

    // Ledger Feed Items
    'ledger.in1': '“Se atendieron 24 niños hoy, entregamos refrigerio a las 10am…”',
    'ledger.out1': '{ attendance: 24, meal_served: true, time: "10:00" }',
    'ledger.status1': 'Validado según Resolución de Salud Pública 003-2024',
    'ledger.in2': '“El centro necesita reponer material didáctico, faltan 3 unidades…”',
    'ledger.out2': '{ supply_request: "didactic_material", qty: 3 }',
    'ledger.status2': 'Marcado para reconciliación presupuestaria',
    'ledger.in3': '“Capacitación de personal completada, asistieron 8 educadoras…”',
    'ledger.out3': '{ training_completed: true, staff_present: 8 }',
    'ledger.status3': 'Reporte de cumplimiento generado',

    // Problem
    'problem.eyebrow': 'El Problema',
    'problem.title': 'Los programas públicos se ahogan en papeleo inauditable.',
    'problem.desc': 'Los reportes en terreno continúan siendo manuales, fragmentados y no rastreables — lo que convierte cada auditoría en una emergencia y cada renovación presupuestaria en una apuesta.',
    'problem.stat1Num': '40%',
    'problem.stat1Label': 'Tiempo operativo perdido',
    'problem.stat1Sub': 'en burocracia manual — Estudio de Eficiencia del Sector Público',
    'problem.stat2Num': 'Severo',
    'problem.stat2Label': 'Riesgo de auditoría y fiscal',
    'problem.stat2Sub': 'El gasto no documentado es la causa #1 de pérdida de fondos públicos',
    'problem.stat3Num': 'Cero',
    'problem.stat3Label': 'Visibilidad en tiempo real',
    'problem.stat3Sub': 'Los directores ven datos semanas después de que ocurren',
    'problem.impact': '~$1B USD / año',
    'problem.impactSub': 'Oportunidad global estimada por digitalizar la administración pública — McKinsey Global Institute',

    // Solution / How
    'how.eyebrow': 'La Solución',
    'how.title': 'Cumplimiento por voz e Inteligencia Agéntica sin fricción.',
    'how.desc': 'Sin aplicaciones complejas que aprender ni formularios manuales. El personal en terreno reporta como ya lo hace a diario.',
    'how.step1Num': '01',
    'how.step1Title': 'Habla, no escribas',
    'how.step1Desc': 'El personal en terreno envía un mensaje de voz por WhatsApp o Telegram — los canales que ya usan todos los días.',
    'how.step2Num': '02',
    'how.step2Title': 'El agente extrae y valida',
    'how.step2Desc': 'Nuestro motor agéntico basado en LangGraph estructura los datos y los valida en tiempo real contra la normativa vigente.',
    'how.step3Num': '03',
    'how.step3Title': 'El cumplimiento se escribe solo',
    'how.step3Desc': 'Cada reporte se convierte en un registro inalterable e inauditable visible para directores y auditores.',

    // Modules
    'modules.eyebrow': 'Arquitectura de Producto',
    'modules.title': 'Un motor de cumplimiento. Múltiples verticales públicas.',
    'modules.desc': 'AI GovCoreX es un sistema operativo RegTech horizontal — cada vertical especializada hereda el mismo motor de cumplimiento y la ingesta por voz.',
    'modules.m1Tag': 'ACTIVO · CABEZA DE PLAYA',
    'modules.m1Title': 'KindiCore AI',
    'modules.m1Desc': 'Gestión de redes de primera infancia y centros infantiles. En producción activa con clientes institucionales.',
    'modules.m2Tag': 'PRÓXIMA VERTICAL',
    'modules.m2Title': 'SocialCore AI',
    'modules.m2Desc': 'Asistencia social, subsidios de movilidad y programas de atención al adulto mayor.',
    'modules.m3Tag': 'HOJA DE RUTA',
    'modules.m3Title': 'HealthCore AI',
    'modules.m3Desc': 'Brigadas de salud comunitaria, nutrición infantil y monitoreo de salud pública en campo.',

    // Traction
    'traction.eyebrow': 'Ejecución Demostrada',
    'traction.title': 'De código a validación e ingresos en 5 meses.',
    'traction.desc': 'Validado con clientes gubernamentales, presupuesto anual renovado y expansión activa.',
    'traction.t1Tag': 'FASE 1',
    'traction.t1Title': 'Despliegue de Sistema Base',
    'traction.t1Sub': 'Arquitectura agéntica construida y optimizada.',
    'traction.t2Tag': 'FASE 2',
    'traction.t2Title': 'Validación Institucional',
    'traction.t2Sub': 'Desplegado en redes de centros municipales.',
    'traction.t3Tag': 'CLIENTE ANCLA',
    'traction.t3Title': 'DASE Guayaquil',
    'traction.t3Sub': 'Presupuesto renovado — cliente ancla retenido.',
    'traction.t4Tag': 'EXPANSIÓN',
    'traction.t4Title': 'Red MIES',
    'traction.t4Sub': '11 centros adicionales en proceso de incorporación.',
    'traction.t5Tag': 'RETENCIÓN',
    'traction.t5Title': '100%',
    'traction.t5Sub': 'Tasa de renovación presupuestaria anual.',

    // Moat
    'moat.eyebrow': 'Foso Defensivo',
    'moat.title': 'Usabilidad por voz + cumplimiento normativo en tiempo real.',
    'moat.desc': 'Ninguna otra plataforma une la captura por voz de cero fricción con la validación estatal automatizada.',
    'moat.q1': 'CRMs Privados (Brightwheel, Procare, ERPs genéricos)',
    'moat.q2': 'AI GovCoreX (OS Agéntico de Compliance Autónomo)',
    'moat.q3': 'Burocracia Manual (Papel y carpetas físicas)',
    'moat.q4': 'Sistemas Gubernamentales Heredados (Tyler Tech, Portales SAP)',
    'moat.axisY': 'USABILIDAD POR VOZ Y CERO FRICCIÓN →',
    'moat.axisX': 'CUMPLIMIENTO NORMATIVO EN TIEMPO REAL →',
    'moat.m1Title': 'Motor de cumplimiento propietario',
    'moat.m1Desc': 'Mapeado directamente contra normativas oficiales, guías de la OMS y reglamentos estatales.',
    'moat.m2Title': 'Altos costos de cambio',
    'moat.m2Desc': 'Incrustado directamente en los flujos de auditoría y líneas de reporte gubernamental.',
    'moat.m3Title': 'Flywheel de datos voz a auditoría',
    'moat.m3Desc': 'Cada nota de voz mejora la precisión de extracción para modismos y vocabulario técnico local.',

    // Footer / CTA
    'footer.ctaTitle': '¿Listo para modernizar la gestión pública?',
    'footer.ctaDesc': 'Únete a las instituciones públicas que están construyendo la nueva era de administración transparente impulsada por IA.',
    'footer.contact': 'Contactar',
    'footer.rights': '© 2026 AI GovCoreX. Sistema Operativo Agéntico de Compliance para el Sector Público. Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.cookies': 'Política de Cookies',
    'footer.terms': 'Términos de Servicio',

    // Beta Register
    'beta.header': 'Lista de Espera Acceso Beta',
    'beta.subtitle': 'Aplica para obtener acceso exclusivo a la plataforma Beta de AI GovCoreX.',
    'beta.step': 'Paso {{current}} de {{total}}',
    'beta.prev': 'Anterior',
    'beta.next': 'Siguiente Paso',
    'beta.submit': 'Solicitar Acceso VIP Beta',
    'beta.submitting': 'Enviando Solicitud...',
    'beta.completedBadge': '¡Solicitud Recibida!',
    'beta.completedTitle': '¡Estás en la Lista de Espera VIP!',
    'beta.completedSubtitle': 'Hemos recibido correctamente la información de {{company}}.',
    'beta.completedDesc': 'Nuestro equipo analizará tus requerimientos y te enviará credenciales a {{email}}.',
    'beta.statusPending': 'Estado: En Evaluación para Incorporación Beta',
    'beta.goToHome': 'Volver a la Página Principal',
    'beta.q1Title': '¿Cuál es el nombre de tu institución u organización?',
    'beta.q1Subtitle': 'Ayúdanos a identificar la entidad que implementará la IA de cumplimiento.',
    'beta.q1Placeholder': 'Ej. Secretaría de Desarrollo Social / Red Municipal de Educación',
    'beta.q1Badge': 'Identidad Organizacional',

    'beta.q2Title': '¿A qué sector o vertical pública pertenece la entidad?',
    'beta.q2Subtitle': 'Permite personalizar las plantillas regulatorias y modelos de voz.',
    'beta.q2Badge': 'Personalización de Vertical',
    'beta.q2Opt1': 'Primera Infancia y Centros Infantiles',
    'beta.q2Opt1Desc': 'Guarderías públicas, redes de atención a la infancia',
    'beta.q2Opt2': 'Asistencia Social y Subsidios',
    'beta.q2Opt2Desc': 'Entrega de ayudas, atención a la vulnerabilidad, adulto mayor',
    'beta.q2Opt3': 'Salud Pública y Brigadas de Nutrición',
    'beta.q2Opt3Desc': 'Centros de salud comunitaria, esquemas de vacunación',
    'beta.q2Opt4': 'Educación y Administración Escolar',
    'beta.q2Opt4Desc': 'Distritos escolares, alimentación escolar, gestión docente',
    'beta.q2Opt5': 'Gobierno Municipal y Local',
    'beta.q2Opt5Desc': 'Alcaldías, operaciones comunitarias, inspecciones en campo',
    'beta.q2Opt6': 'Otro Sector Público / B2G',
    'beta.q2Opt6Desc': 'Otras entidades gubernamentales u organizaciones sociales',

    'beta.q3Title': '¿Cuántos centros o trabajadores en campo operan en su red?',
    'beta.q3Subtitle': 'Ayuda a dimensionar la capacidad de cómputo necesaria.',
    'beta.q3Badge': 'Evaluación de Escala',
    'beta.q3Opt1': '1 a 5 centros / trabajadores',
    'beta.q3Opt1Desc': 'Programas pequeños o redes piloto',
    'beta.q3Opt2': '6 a 20 centros / trabajadores',
    'beta.q3Opt2Desc': 'Redes municipales en crecimiento',
    'beta.q3Opt3': '21 a 50 centros / trabajadores',
    'beta.q3Opt3Desc': 'Programas regionales de asistencia social',
    'beta.q3Opt4': 'Más de 50 centros / trabajadores',
    'beta.q3Opt4Desc': 'Redes estatales o nacionales (Enterprise Gov)',

    'beta.q4Title': '¿Qué flujo o reportes en campo necesitan automatizar?',
    'beta.q4Subtitle': 'Describe brevemente las tareas operativas principales de tu equipo.',
    'beta.q4Badge': 'Alcance Operativo',
    'beta.q4Placeholder': 'Ej. Control diario de asistencia, entrega de alimentos, controles de desarrollo infantil, minutas de auditoría...',

    'beta.q5Title': '¿Cuál es el nivel actual de adopción tecnológica o IA en su entidad?',
    'beta.q5Subtitle': 'Identifica la etapa tecnológica actual.',
    'beta.q5Badge': 'Madurez Digital',
    'beta.q5Opt1': 'Nivel Inicial / Primera Vez',
    'beta.q5Opt1Desc': 'Uso personal puntual (ChatGPT), sin integración institucional',
    'beta.q5Opt2': 'Nivel Intermedio',
    'beta.q5Opt2Desc': 'Herramientas básicas de automatización, formatos manuales o chatbots',
    'beta.q5Opt3': 'Nivel Avanzado',
    'beta.q5Opt3Desc': 'Flujos automatizados que buscan un OS de IA agéntica autónoma',

    'beta.q6Title': '¿Qué objetivos principales buscan lograr con AI GovCoreX?',
    'beta.q6Subtitle': 'Tus metas guiarán la configuración de los agentes.',
    'beta.q6Badge': 'Objetivo Clave',
    'beta.q6Placeholder': 'Ej. Eliminar papel impreso, tener auditoría instantánea para inspecciones estatales, capturar notas de voz por WhatsApp...',

    'beta.q7Title': '¡Casi listos! Ingresa tus datos institucionales de contacto',
    'beta.q7Subtitle': 'Enviaremos tu confirmación y credenciales a estas vías.',
    'beta.q7Badge': 'Paso Final',
    'beta.q7Name': 'Nombre Completo',
    'beta.q7NamePh': 'Ej. Carlos Mendoza',
    'beta.q7Role': 'Cargo Oficial / Título',
    'beta.q7RolePh': 'Ej. Director de Operaciones / Coordinador de Programa',
    'beta.q7Email': 'Correo Electrónico Oficial',
    'beta.q7EmailPh': 'carlos@gobierno.gob.ec',
    'beta.q7Phone': 'Teléfono / WhatsApp',
    'beta.q7PhonePh': '+593 99 123 4567',
    'beta.q7Security': 'Tus datos están protegidos con cifrado SSL de grado institucional.',

    'beta.valText': 'Por favor completa este campo para continuar.',
    'beta.valSelect': 'Por favor selecciona una opción para avanzar.',
    'beta.valContact': 'Por favor completa todos los datos de contacto requeridos.',

    // Legal pages
    'legal.termsTitle': 'Términos de Servicio',
    'legal.privacyTitle': 'Política de Privacidad y Seguridad de Datos',
    'legal.lastUpdated': 'Última actualización: Agosto 2026',
    'legal.backHome': 'Volver a AI GovCoreX',
    'legal.privacySec1Title': '1. Protección de Datos y Cumplimiento Público',
    'legal.privacySec1Text': 'AI GovCoreX emplea aislamiento de base de datos multi-tenant, cifrado SSL y estricto control de acceso basado en roles (RBAC). Todos los datos de cumplimiento y reportes de voz en campo se almacenan en entornos cloud seguros conformes a estándares de privacidad estatales e internacionales.',
    'legal.privacySec2Title': '2. Uso de la Información Recopilada',
    'legal.privacySec2Text': 'La información ingresada en el registro de lista de espera Beta se utiliza exclusivamente para la calificación de la entidad, estimación de capacidad de procesamiento y entrega de credenciales de acceso.',
    'legal.privacySec3Title': '3. Seguridad de la Información',
    'legal.privacySec3Text': 'Implementamos salvaguardas administrativas y técnicas para prevenir accesos no autorizados, divulgación o alteración de los registros de programas públicos.',
    'legal.termsSec1Title': '1. Servicios de Plataforma y Gobernanza',
    'legal.termsSec1Text': 'AI GovCoreX provee un sistema operativo agéntico autónomo de cumplimiento diseñado para entidades públicas, contratistas gubernamentales y administradores de programas sociales. Al registrarse, las entidades aceptan los protocolos de cumplimiento del sector público y privacidad de datos.',
    'legal.termsSec2Title': '2. Procesamiento de Notas de Voz e IA Agéntica',
    'legal.termsSec2Text': 'Los reportes de audio de campo enviados vía canales oficiales (WhatsApp, Telegram) son procesados por modelos de extracción de lenguaje natural ajustados estrictamente a las normativas de cada programa. Ningún dato de audio se comparte con terceros no autorizados.',
    'legal.termsSec3Title': '3. Propiedad Intelectual y Arquitectura Modular',
    'legal.termsSec3Text': 'AI GovCoreX y sus módulos verticales (incluyendo KindiCore AI, SocialCore AI y HealthCore AI) son propiedad intelectual exclusiva de la entidad matriz.'
  },

  pt: {
    // Nav
    'nav.product': 'Arquitetura de Produto',
    'nav.how': 'Como Funciona',
    'nav.traction': 'Tração',
    'nav.legal': 'Legal',
    'nav.demo': 'Solicitar Demo',
    'nav.beta': 'Lista de Espera',
    'nav.dashboard': 'Painel de Gestão',
    'nav.login': 'Entrar',

    // Hero
    'hero.eyebrow': 'Sistema Operacional Agêntico de Compliance',
    'hero.title1': 'Transforme notas de voz em ',
    'hero.titleAccent': 'registros prontos para auditoria.',
    'hero.lead': 'O AI GovCoreX é a infraestrutura de conformidade usada por governos para gerenciar programas sociais, primeira infância e saúde com captura por voz sem fricção.',
    'hero.ctaPrimary': 'Participar da Lista Beta',
    'hero.ctaSecondary': 'Ver Como Funciona',
    'hero.trust1': 'Em produção em redes municipais',
    'hero.trust2': '11 centros em integração institucional',
    'hero.trust3': '100% de renovação orçamentária anual',
    'hero.ledgerTitle': 'LIVRO RAZÃO DE COMPLIANCE EM TEMPO REAL',
    'hero.ledgerEngine': 'motor: langgraph-agentic-v2',
    'hero.ledgerRegion': 'região: nuvem-global-01',

    // Ledger Feed Items
    'ledger.in1': '“24 crianças atendidas hoje, refeição servida às 10h…”',
    'ledger.out1': '{ attendance: 24, meal_served: true, time: "10:00" }',
    'ledger.status1': 'Validado conforme Resolução de Saúde Pública',
    'ledger.in2': '“Centro precisa repor material didático, faltam 3 unidades…”',
    'ledger.out2': '{ supply_request: "didactic_material", qty: 3 }',
    'ledger.status2': 'Sinalizado para reconciliação orçamentária',
    'ledger.in3': '“Treinamento concluído, 8 educadoras presentes…”',
    'ledger.out3': '{ training_completed: true, staff_present: 8 }',
    'ledger.status3': 'Relatório de conformidade gerado',

    // Problem
    'problem.eyebrow': 'O Problema',
    'problem.title': 'Programas públicos afundados em burocracia manual.',
    'problem.desc': 'Relatórios de campo em programas sociais permanecem manuais e sem rastreabilidade — transformando cada auditoria em um risco.',
    'problem.stat1Num': '40%',
    'problem.stat1Label': 'Tempo operacional perdido',
    'problem.stat1Sub': 'em burocracia manual — Benchmark do Setor Público',
    'problem.stat2Num': 'Severo',
    'problem.stat2Label': 'Risco fiscal e de auditoria',
    'problem.stat2Sub': 'Gastos não documentados são a causa #1 de perda de verbas públicas',
    'problem.stat3Num': 'Zero',
    'problem.stat3Label': 'Visibilidade em tempo real',
    'problem.stat3Sub': 'Gestores veem dados semanas após os acontecimentos',
    'problem.impact': '~$1 Tri USD / ano',
    'problem.impactSub': 'Oportunidade global estimada com digitalização do setor público — McKinsey',

    // Solution / How
    'how.eyebrow': 'A Solução',
    'how.title': 'Conformidade por voz e IA agêntica sem fricção.',
    'how.desc': 'Sem novos aplicativos complexos. Equipes de campo reportam como já fazem no dia a dia.',
    'how.step1Num': '01',
    'how.step1Title': 'Fale, não digite',
    'how.step1Desc': 'Trabalhadores enviam notas de voz no WhatsApp ou Telegram.',
    'how.step2Num': '02',
    'how.step2Title': 'Agente extrai e valida',
    'how.step2Desc': 'O motor agêntico LangGraph valida as informações em tempo real.',
    'how.step3Num': '03',
    'how.step3Title': 'Relatórios automáticos',
    'how.step3Desc': 'Cada relatório torna-se um registro auditável instantâneo.',

    // Modules
    'modules.eyebrow': 'Arquitetura de Produto',
    'modules.title': 'Um motor de compliance. Múltiplas verticais públicas.',
    'modules.desc': 'AI GovCoreX é um OS RegTech horizontal projetado para escala governamental.',
    'modules.m1Tag': 'ATIVO · PRIMEIRA INFÂNCIA',
    'modules.m1Title': 'KindiCore AI',
    'modules.m1Desc': 'Gestão de creches e desenvolvimento infantil. Em produção ativa.',
    'modules.m2Tag': 'PRÓXIMA VERTICAL',
    'modules.m2Title': 'SocialCore AI',
    'modules.m2Desc': 'Programas de assistência social, subsídios e cuidados com idosos.',
    'modules.m3Tag': 'PLANO FUTURO',
    'modules.m3Title': 'HealthCore AI',
    'modules.m3Desc': 'Brigadas de saúde comunitária e nutrição infantil.',

    // Traction
    'traction.eyebrow': 'Execução Demonstrada',
    'traction.title': 'Do código à adoção institucional em 5 meses.',
    'traction.desc': 'Validado com governos locais e renovação de contratos anuais.',
    'traction.t1Tag': 'FASE 1',
    'traction.t1Title': 'Sistema Base Implantado',
    'traction.t1Sub': 'Arquitetura agêntica validada.',
    'traction.t2Tag': 'FASE 2',
    'traction.t2Title': 'Validação Institucional',
    'traction.t2Sub': 'Implantado em redes públicas municipais.',
    'traction.t3Tag': 'CLIENTE ÂNCORA',
    'traction.t3Title': 'DASE Guayaquil',
    'traction.t3Sub': 'Contrato renovado no orçamento anual.',
    'traction.t4Tag': 'EXPANSÃO',
    'traction.t4Title': 'Rede MIES',
    'traction.t4Sub': '11 centros em integração institucional.',
    'traction.t5Tag': 'RETENÇÃO',
    'traction.t5Title': '100%',
    'traction.t5Sub': 'Taxa de renovação orçamentária anual.',

    // Moat
    'moat.eyebrow': 'Diferencial Competitivo',
    'moat.title': 'Usabilidade por voz + conformidade estatal instantânea.',
    'moat.desc': 'Captura por áudio conectada diretamente a regras regulatórias.',
    'moat.q1': 'CRMs Privados Tradicionais',
    'moat.q2': 'AI GovCoreX (OS Agêntico de Compliance)',
    'moat.q3': 'Burocracia Manual em Papel',
    'moat.q4': 'Sistemas Legados do Governo',
    'moat.axisY': 'USABILIDADE POR VOZ →',
    'moat.axisX': 'CONFORMIDADE EM TEMPO REAL →',
    'moat.m1Title': 'Motor de conformidade proprietário',
    'moat.m1Desc': 'Mapeado diretamente para normas públicas estatais e OMS.',
    'moat.m2Title': 'Altos custos de troca',
    'moat.m2Desc': 'Integrado aos fluxos de auditoria governamental.',
    'moat.m3Title': 'Flywheel de voz para auditoria',
    'moat.m3Desc': 'Cada áudio aprimora a precisão do modelo.',

    // Footer / CTA
    'footer.ctaTitle': 'Pronto para modernizar o setor público?',
    'footer.ctaDesc': 'Junte-se às instituições que estão construindo a gestão pública do futuro.',
    'footer.contact': 'Contato',
    'footer.rights': '© 2026 AI GovCoreX. Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',

    // Beta Register
    'beta.header': 'Lista de Espera Beta',
    'beta.subtitle': 'Inscreva-se para obter acesso exclusivo à plataforma AI GovCoreX.',
    'beta.step': 'Passo {{current}} de {{total}}',
    'beta.prev': 'Anterior',
    'beta.next': 'Próximo Passo',
    'beta.submit': 'Solicitar Acesso VIP Beta',
    'beta.submitting': 'Enviando...',
    'beta.completedBadge': 'Solicitação Recebida!',
    'beta.completedTitle': 'Você está na Lista VIP!',
    'beta.completedSubtitle': 'Recebemos as informações de {{company}}.',
    'beta.completedDesc': 'Nossa equipe analisará seus dados e enviará as credenciais para {{email}}.',
    'beta.statusPending': 'Status: Em Avaliação',
    'beta.goToHome': 'Voltar à Página Inicial',
    'beta.q1Title': 'Qual o nome da sua organização ou entidade pública?',
    'beta.q1Subtitle': 'Identifique a entidade que usará a IA de conformidade.',
    'beta.q1Placeholder': 'Ex. Secretaria de Ação Social / Rede Municipal',
    'beta.q1Badge': 'Identidade Organizacional',

    'beta.q2Title': 'Qual setor público sua entidade atua?',
    'beta.q2Subtitle': 'Permite personalizar os modelos de voz e relatórios.',
    'beta.q2Badge': 'Setor de Atuação',
    'beta.q2Opt1': 'Primeira Infância e Creches',
    'beta.q2Opt1Desc': 'Creches públicas e atendimento infantil',
    'beta.q2Opt2': 'Assistência Social e Subsídios',
    'beta.q2Opt2Desc': 'Programas sociais e apoio à vulnerabilidade',
    'beta.q2Opt3': 'Saúde Pública e Nutrição',
    'beta.q2Opt3Desc': 'Postos de saúde e brigadas nutricionais',
    'beta.q2Opt4': 'Educação Pública',
    'beta.q2Opt4Desc': 'Escolas municipais e merenda escolar',
    'beta.q2Opt5': 'Gestão Municipal e Local',
    'beta.q2Opt5Desc': 'Prefeituras e fiscalização de campo',
    'beta.q2Opt6': 'Outro Setor Público',
    'beta.q2Opt6Desc': 'Outros prestadores ou ONGs parceiras',

    'beta.q3Title': 'Quantos centros ou agentes operam na sua rede?',
    'beta.q3Subtitle': 'Ajuda a dimensionar a capacidade necessária.',
    'beta.q3Badge': 'Escala Operacional',
    'beta.q3Opt1': '1 a 5 centros / agentes',
    'beta.q3Opt1Desc': 'Projetos piloto ou pequenas redes',
    'beta.q3Opt2': '6 a 20 centros / agentes',
    'beta.q3Opt2Desc': 'Redes municipais em expansão',
    'beta.q3Opt3': '21 a 50 centros / agentes',
    'beta.q3Opt3Desc': 'Programas regionais',
    'beta.q3Opt4': 'Mais de 50 centros / agentes',
    'beta.q3Opt4Desc': 'Redes estaduais/nacionais (Enterprise)',

    'beta.q4Title': 'Quais relatórios de campo vocês precisam automatizar?',
    'beta.q4Subtitle': 'Descreva brevemente as rotinas operacionais diárias.',
    'beta.q4Badge': 'Escopo Operacional',
    'beta.q4Placeholder': 'Ex. Presença diária, distribuição de alimentos, visitas domiciliares...',

    'beta.q5Title': 'Qual o nível atual de adoção de IA na sua instituição?',
    'beta.q5Subtitle': 'Identifica a maturidade tecnológica atual.',
    'beta.q5Badge': 'Maturidade Digital',
    'beta.q5Opt1': 'Iniciante / Primeiros Passos',
    'beta.q5Opt1Desc': 'Uso pontual de ferramentas como ChatGPT',
    'beta.q5Opt2': 'Intermediário',
    'beta.q5Opt2Desc': 'Formulários básicos ou chatbots simples',
    'beta.q5Opt3': 'Avançado',
    'beta.q5Opt3Desc': 'Buscando automatização agêntica completa',

    'beta.q6Title': 'Quais os principais objetivos com o AI GovCoreX?',
    'beta.q6Subtitle': 'Seus objetivos guiarão a configuração inicial.',
    'beta.q6Badge': 'Objetivo Principal',
    'beta.q6Placeholder': 'Ex. Eliminar papéis, ter auditoria em tempo real, capturar áudios no WhatsApp...',

    'beta.q7Title': 'Quase pronto! Informe seus dados institucionais',
    'beta.q7Subtitle': 'Enviaremos seu acesso para estes contatos.',
    'beta.q7Badge': 'Passo Final',
    'beta.q7Name': 'Nome Completo',
    'beta.q7NamePh': 'Ex. Roberto Silva',
    'beta.q7Role': 'Cargo / Função',
    'beta.q7RolePh': 'Ex. Diretor de Operações',
    'beta.q7Email': 'E-mail Oficial',
    'beta.q7EmailPh': 'roberto@gov.br',
    'beta.q7Phone': 'Telefone / WhatsApp',
    'beta.q7PhonePh': '+55 (11) 98765-4321',
    'beta.q7Security': 'Seus dados estão protegidos com criptografia SSL.',

    'beta.valText': 'Por favor, preencha este campo para continuar.',
    'beta.valSelect': 'Por favor, selecione uma opção.',
    'beta.valContact': 'Por favor, preencha todos os campos de contato.',

    // Legal pages
    'legal.termsTitle': 'Termos de Serviço',
    'legal.privacyTitle': 'Política de Privacidade e Segurança de Dados',
    'legal.lastUpdated': 'Última atualização: Agosto de 2026',
    'legal.backHome': 'Voltar para AI GovCoreX',
    'legal.privacySec1Title': '1. Proteção de Dados e Conformidade Pública',
    'legal.privacySec1Text': 'O AI GovCoreX emprega isolamento de banco de dados multi-tenant, criptografia SSL e estrito controle de acesso baseado em funções (RBAC). Todos os dados de conformidade e relatórios de voz de campo são armazenados em nuvem segura em conformidade com padrões de privacidade governamentais.',
    'legal.privacySec2Title': '2. Uso das Informações Coletadas',
    'legal.privacySec2Text': 'As informações submetidas no cadastro da lista de espera Beta são usadas exclusivamente para qualificação da organização, dimensionamento de infraestrutura e entrega de credenciais de acesso.',
    'legal.privacySec3Title': '3. Segurança da Informação',
    'legal.privacySec3Text': 'Implementamos salvaguardas técnicas e administrativas para evitar acesso não autorizado, divulgação ou alteração de registros de programas públicos.',
    'legal.termsSec1Title': '1. Serviços de Plataforma e Governança',
    'legal.termsSec1Text': 'O AI GovCoreX fornece um sistema operacional agêntico de conformidade para agências do setor público e gestores de programas sociais. Ao se cadastrar, as entidades concordam com os protocolos de conformidade pública e privacidade de dados.',
    'legal.termsSec2Title': '2. Processamento de Voz e IA Agêntica',
    'legal.termsSec2Text': 'Áudios enviados via canais oficiais (WhatsApp, Telegram) são processados por modelos de linguagem natural estritamente alinhados aos marcos regulatórios de cada programa. Nenhum dado de áudio é compartilhado com terceiros não autorizados.',
    'legal.termsSec3Title': '3. Propriedade Intelectual e Arquitetura Modular',
    'legal.termsSec3Text': 'O AI GovCoreX e seus módulos verticais (incluindo KindiCore AI, SocialCore AI e HealthCore AI) permanecem como propriedade intelectual exclusiva da entidade matriz.'
  },

  fr: {
    // Nav
    'nav.product': 'Architecture Produit',
    'nav.how': 'Comment ça marche',
    'nav.traction': 'Traction',
    'nav.legal': 'Légal',
    'nav.demo': 'Demander une démo',
    'nav.beta': 'Rejoindre la liste VIP',
    'nav.dashboard': 'Tableau de bord',
    'nav.login': 'Connexion',

    // Hero
    'hero.eyebrow': 'Système d’Exploration Agentique de Conformité',
    'hero.title1': 'Transformez une note vocale en ',
    'hero.titleAccent': 'registre prêt pour l’audit.',
    'hero.lead': 'AI GovCoreX est l’infrastructure de conformité utilisée par les gouvernements pour gérer la petite enfance et les programmes sociaux avec capture vocale sans friction.',
    'hero.ctaPrimary': 'Rejoindre la Liste Beta',
    'hero.ctaSecondary': 'Voir le Fonctionnement',
    'hero.trust1': 'En production dans les réseaux municipaux',
    'hero.trust2': '11 centres en intégration institutionnelle',
    'hero.trust3': '100% de renouvellement budgétaire annuel',
    'hero.ledgerTitle': 'REGISTRE DE CONFORMITÉ EN DIRECT',
    'hero.ledgerEngine': 'moteur: langgraph-agentic-v2',
    'hero.ledgerRegion': 'région: nuage-global-01',

    // Ledger Feed Items
    'ledger.in1': '“24 enfants accueillis ce jour, repas servi à 10h…”',
    'ledger.out1': '{ attendance: 24, meal_served: true, time: "10:00" }',
    'ledger.status1': 'Validé selon les réglementations de santé publique',
    'ledger.in2': '“Reconstitution de matériel pédagogique requise…”',
    'ledger.out2': '{ supply_request: "didactic_material", qty: 3 }',
    'ledger.status2': 'Signalé pour réconciliation budgétaire',
    'ledger.in3': '“Formation terminée, 8 éducatrices présentes…”',
    'ledger.out3': '{ training_completed: true, staff_present: 8 }',
    'ledger.status3': 'Rapport de conformité généré',

    // Problem
    'problem.eyebrow': 'Le Problème',
    'problem.title': 'Les programmes publics étouffent sous la paperasse.',
    'problem.desc': 'Le reporting de terrain reste manuel et non traçable — transformant chaque audit en situation de crise.',
    'problem.stat1Num': '40%',
    'problem.stat1Label': 'Temps opérationnel perdu',
    'problem.stat1Sub': 'en bureaucratie manuelle — Indice du Secteur Public',
    'problem.stat2Num': 'Sévère',
    'problem.stat2Label': 'Risque fiscal et d’audit',
    'problem.stat2Sub': 'Les dépenses non documentées causent la perte des budgets publics',
    'problem.stat3Num': 'Zéro',
    'problem.stat3Label': 'Visibilité en temps réel',
    'problem.stat3Sub': 'Les décideurs voient les données des semaines après les faits',
    'problem.impact': '~$1000 Mds / an',
    'problem.impactSub': 'Opportunité globale de numérisation du secteur public — McKinsey',

    // Solution / How
    'how.eyebrow': 'La Solution',
    'how.title': 'Conformité vocale et IA agentique sans friction.',
    'how.desc': 'Aucune application complexe à apprendre. Les agents de terrain rapportent via leurs canaux habituels.',
    'how.step1Num': '01',
    'how.step1Title': 'Parlez, ne tapez pas',
    'how.step1Desc': 'Les agents envoient une note vocale sur WhatsApp ou Telegram.',
    'how.step2Num': '02',
    'how.step2Title': 'L’agent extrait et valide',
    'how.step2Desc': 'Le moteur LangGraph structure et valide les données en temps réel.',
    'how.step3Num': '03',
    'how.step3Title': 'Audit automatique',
    'how.step3Desc': 'Chaque rapport devient un enregistrement infalsifiable.',

    // Modules
    'modules.eyebrow': 'Architecture Produit',
    'modules.title': 'Un moteur de conformité. Plusieurs verticales publiques.',
    'modules.desc': 'AI GovCoreX est un OS RegTech horizontal conçu pour l’administration publique.',
    'modules.m1Tag': 'ACTIF · PETITE ENFANCE',
    'modules.m1Title': 'KindiCore AI',
    'modules.m1Desc': 'Gestion des réseaux de petite enfance et crèches. En production.',
    'modules.m2Tag': 'PROCHAINE VERTICALE',
    'modules.m2Title': 'SocialCore AI',
    'modules.m2Desc': 'Programmes d’aide sociale, subventions et prise en charge des séniors.',
    'modules.m3Tag': 'FEUILLE DE ROUTE',
    'modules.m3Title': 'HealthCore AI',
    'modules.m3Desc': 'Brigades de santé communautaire et nutrition infantile.',

    // Traction
    'traction.eyebrow': 'Exécution Prouvée',
    'traction.title': 'Du code à l’adoption gouvernementale en 5 mois.',
    'traction.desc': 'Validé auprès de réseaux publics avec renouvellement budgétaire.',
    'traction.t1Tag': 'PHASE 1',
    'traction.t1Title': 'Système de Base Déployé',
    'traction.t1Sub': 'Architecture agentique opérationnelle.',
    'traction.t2Tag': 'PHASE 2',
    'traction.t2Title': 'Validation Institutionnelle',
    'traction.t2Sub': 'Déployé dans les réseaux municipaux.',
    'traction.t3Tag': 'CLIENT ANCRE',
    'traction.t3Title': 'DASE Guayaquil',
    'traction.t3Sub': 'Budget renouvelé dans le plan annuel.',
    'traction.t4Tag': 'EXPANSION',
    'traction.t4Title': 'Réseau MIES',
    'traction.t4Sub': '11 centres supplémentaires en intégration.',
    'traction.t5Tag': 'RÉTENTION',
    'traction.t5Title': '100%',
    'traction.t5Sub': 'Taux de renouvellement budgétaire annuel.',

    // Moat
    'moat.eyebrow': 'Avantage Compétitif',
    'moat.title': 'Usabilité vocale + conformité réglementaire directe.',
    'moat.desc': 'La seule plateforme connectant la voix sur le terrain aux réglementations d’État.',
    'moat.q1': 'Logiciels CRM Classiques',
    'moat.q2': 'AI GovCoreX (OS Agentique de Conformité)',
    'moat.q3': 'Bureaucratie Manuelle Papier',
    'moat.q4': 'Systèmes Étatiques Hérités',
    'moat.axisY': 'USABILITÉ VOCALE →',
    'moat.axisX': 'CONFORMITÉ TEMPS RÉEL →',
    'moat.m1Title': 'Moteur de conformité propriétaire',
    'moat.m1Desc': 'Directement aligné sur les normes officielles et l’OMS.',
    'moat.m2Title': 'Coûts de changement élevés',
    'moat.m2Desc': 'Intégré au cœur des lignes de contrôle public.',
    'moat.m3Title': 'Flywheel voix vers audit',
    'moat.m3Desc': 'Chaque note améliore la précision linguistique locale.',

    // Footer / CTA
    'footer.ctaTitle': 'Prêt à moderniser la gestion publique ?',
    'footer.ctaDesc': 'Rejoignez les institutions qui construisent l’administration publique de demain.',
    'footer.contact': 'Nous contacter',
    'footer.rights': '© 2026 AI GovCoreX. Tous droits réservés.',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d’utilisation',

    // Beta Register
    'beta.header': 'Liste d’Attente Beta',
    'beta.subtitle': 'Demandez votre accès exclusif à la plateforme AI GovCoreX.',
    'beta.step': 'Étape {{current}} sur {{total}}',
    'beta.prev': 'Précédent',
    'beta.next': 'Étape Suivante',
    'beta.submit': 'Demander l’Accès VIP Beta',
    'beta.submitting': 'Envoi en cours...',
    'beta.completedBadge': 'Demande Reçue !',
    'beta.completedTitle': 'Vous êtes sur la Liste VIP !',
    'beta.completedSubtitle': 'Nous avons bien enregistré les informations de {{company}}.',
    'beta.completedDesc': 'Notre équipe analysera vos besoins et vous enverra vos accès à {{email}}.',
    'beta.statusPending': 'Statut: En cours d’évaluation',
    'beta.goToHome': 'Retour à l’Accueil',
    'beta.q1Title': 'Quel est le nom de votre organisation ou entité publique ?',
    'beta.q1Subtitle': 'Identifiez l’entité qui utilisera l’IA de conformité.',
    'beta.q1Placeholder': 'Ex. Ministère de l’Action Sociale / Région',
    'beta.q1Badge': 'Identité Organisationnelle',

    'beta.q2Title': 'Dans quel secteur public opérez-vous ?',
    'beta.q2Subtitle': 'Permet d’adapter les modèles vocaux et réglementaires.',
    'beta.q2Badge': 'Secteur d’Activité',
    'beta.q2Opt1': 'Petite Enfance & Crèches',
    'beta.q2Opt1Desc': 'Réseaux de crèches publiques et petite enfance',
    'beta.q2Opt2': 'Action Sociale & Subventions',
    'beta.q2Opt2Desc': 'Aides sociales, soutien à la vulnérabilité',
    'beta.q2Opt3': 'Santé Publique & Nutrition',
    'beta.q2Opt3Desc': 'Centres de santé communautaire et nutrition',
    'beta.q2Opt4': 'Éducation & Écoles',
    'beta.q2Opt4Desc': 'Établissements scolaires publics et cantines',
    'beta.q2Opt5': 'Administration Municipale',
    'beta.q2Opt5Desc': 'Services municipaux et inspections de terrain',
    'beta.q2Opt6': 'Autre Secteur Public',
    'beta.q2Opt6Desc': 'Autres prestataires gouvernementaux',

    'beta.q3Title': 'Combien de centres ou d’agents opèrent dans votre réseau ?',
    'beta.q3Subtitle': 'Permet d’évaluer la capacité système nécessaire.',
    'beta.q3Badge': 'Échelle d’Opération',
    'beta.q3Opt1': '1 à 5 centres / agents',
    'beta.q3Opt1Desc': 'Projets pilotes ou petits réseaux',
    'beta.q3Opt2': '6 à 20 centres / agents',
    'beta.q3Opt2Desc': 'Réseaux municipaux en expansion',
    'beta.q3Opt3': '21 à 50 centres / agents',
    'beta.q3Opt3Desc': 'Programmes régionaux',
    'beta.q3Opt4': 'Plus de 50 centres / agents',
    'beta.q3Opt4Desc': 'Réseaux nationaux (Enterprise Gov)',

    'beta.q4Title': 'Quels rapports de terrain souhaitez-vous automatiser ?',
    'beta.q4Subtitle': 'Décrivez brièvement vos activités quotidiennes.',
    'beta.q4Badge': 'Périmètre Opérationnel',
    'beta.q4Placeholder': 'Ex. Présence quotidienne, distribution de repas, suivis sanitaires...',

    'beta.q5Title': 'Quel est le niveau actuel d’adoption de l’IA dans votre entité ?',
    'beta.q5Subtitle': 'Identifie votre maturité numérique.',
    'beta.q5Badge': 'Maturité Numérique',
    'beta.q5Opt1': 'Niveau Initial / Débutant',
    'beta.q5Opt1Desc': 'Utilisation personnelle occasionnelle (ChatGPT)',
    'beta.q5Opt2': 'Niveau Intermédiaire',
    'beta.q5Opt2Desc': 'Formulaires simples ou chatbots de base',
    'beta.q5Opt3': 'Niveau Avancé',
    'beta.q5Opt3Desc': 'Recherche d’automatisation agentique complète',

    'beta.q6Title': 'Quels sont vos objectifs principaux avec AI GovCoreX ?',
    'beta.q6Subtitle': 'Vos objectifs guideront la configuration initiale.',
    'beta.q6Badge': 'Objectif Clé',
    'beta.q6Placeholder': 'Ex. Éliminer le papier, obtenir des audits en temps réel, capturer la voix via WhatsApp...',

    'beta.q7Title': 'Presque terminé ! Saisissez vos coordonnées officielles',
    'beta.q7Subtitle': 'Nous vous enverrons vos accès à ces coordonnées.',
    'beta.q7Badge': 'Dernière Étape',
    'beta.q7Name': 'Nom Complet',
    'beta.q7NamePh': 'Ex. Antoine Dupont',
    'beta.q7Role': 'Titre / Fonction Officielle',
    'beta.q7RolePh': 'Ex. Directeur des Opérations',
    'beta.q7Email': 'Adresse E-mail Officielle',
    'beta.q7EmailPh': 'antoine@gouv.fr',
    'beta.q7Phone': 'Téléphone / WhatsApp',
    'beta.q7PhonePh': '+33 6 12 34 56 78',
    'beta.q7Security': 'Vos données sont protégées par chiffrement SSL.',

    'beta.valText': 'Veuillez remplir ce champ pour continuer.',
    'beta.valSelect': 'Veuillez sélectionner une option.',
    'beta.valContact': 'Veuillez remplir tous les champs de contact.',

    // Legal pages
    'legal.termsTitle': 'Conditions d’Utilisation',
    'legal.privacyTitle': 'Politique de Confidentialité et Sécurité des Données',
    'legal.lastUpdated': 'Dernière mise à jour : Août 2026',
    'legal.backHome': 'Retour à AI GovCoreX',
    'legal.privacySec1Title': '1. Protection des Données et Conformité Publique',
    'legal.privacySec1Text': 'AI GovCoreX applique une isolation de base de données multi-tenant, un chiffrement SSL et un contrôle d’accès strict basé sur les rôles (RBAC). Toutes les données de conformité et notes vocales de terrain sont stockées dans des environnements cloud sécurisés conformes aux normes étatiques et internationales.',
    'legal.privacySec2Title': '2. Utilisation des Informations Collectées',
    'legal.privacySec2Text': 'Les informations soumises via l’inscription sur la liste VIP sont exclusivement utilisées pour la qualification institutionnelle, le dimensionnement de charge et la remise des identifiants d’accès.',
    'legal.privacySec3Title': '3. Sécurité de l’Information',
    'legal.privacySec3Text': 'Nous mettons en œuvre des mesures de protection administratives et techniques pour prévenir tout accès, divulgation ou altération non autorisés des registres de programmes publics.',
    'legal.termsSec1Title': '1. Services de la Plateforme et Gouvernance',
    'legal.termsSec1Text': 'AI GovCoreX fournit un système d’exploitation agentique autonome de conformité conçu pour les organismes publics et administrateurs de programmes sociaux. En s’inscrivant, les entités acceptent les protocoles de conformité publique et de confidentialité des données.',
    'legal.termsSec2Title': '2. Données Vocales et Traitement Agentique',
    'legal.termsSec2Text': 'Les rapports audio de terrain envoyés via les canaux officiels (WhatsApp, Telegram) sont traités par des modèles d’extraction de langage naturel strictement cadrés par les réglementations des programmes. Aucune donnée audio n’est partagée avec des tiers non autorisés.',
    'legal.termsSec3Title': '3. Propriété Intellectuelle et Architecture Modulaire',
    'legal.termsSec3Text': 'AI GovCoreX et ses modules verticaux (notamment KindiCore AI, SocialCore AI et HealthCore AI) demeurent la propriété intellectuelle exclusive de l’entité mère.'
  },

  de: {
    // Nav
    'nav.product': 'Produktarchitektur',
    'nav.how': 'Wie es funktioniert',
    'nav.traction': 'Erfolge & Traktion',
    'nav.legal': 'Rechtliches',
    'nav.demo': 'Demo anfordern',
    'nav.beta': 'Auf die Warteliste',
    'nav.dashboard': 'Verwaltungs-Panel',
    'nav.login': 'Anmelden',

    // Hero
    'hero.eyebrow': 'Autonomes Agenten-Compliance-OS',
    'hero.title1': 'Verwandeln Sie Sprachnotizen in ',
    'hero.titleAccent': 'prüfungsbereite Berichte.',
    'hero.lead': 'AI GovCoreX ist die Compliance-Infrastruktur für öffentliche Programme, frühkindliche Bildung und Sozialwesen mit reibungsloser Sprachaufzeichnung und Echtzeit-Transparenz.',
    'hero.ctaPrimary': 'Zur Beta-Warteliste',
    'hero.ctaSecondary': 'Funktionsweise ansehen',
    'hero.trust1': 'In Produktion bei kommunalen Netzwerken',
    'hero.trust2': '11 öffentliche Zentren im Onboarding',
    'hero.trust3': '100% jährliche Budgetverlängerung',
    'hero.ledgerTitle': 'LIVE COMPLIANCE LEDGER',
    'hero.ledgerEngine': 'Engine: langgraph-agentic-v2',
    'hero.ledgerRegion': 'Region: Cloud-Global-01',

    // Ledger Feed Items
    'ledger.in1': '“24 Kinder heute anwesend, Frühstück um 10 Uhr serviert…”',
    'ledger.out1': '{ attendance: 24, meal_served: true, time: "10:00" }',
    'ledger.status1': 'Validiert nach öffentlichen Gesundheitsrichtlinien',
    'ledger.in2': '“Zentrum benötigt Nachschub an Lernmaterialien…”',
    'ledger.out2': '{ supply_request: "didactic_material", qty: 3 }',
    'ledger.status2': 'Für Budgetabgleich markiert',
    'ledger.in3': '“Personal-Schulung abgeschlossen, 8 Erzieherinnen anwesend…”',
    'ledger.out3': '{ training_completed: true, staff_present: 8 }',
    'ledger.status3': 'Compliance-Bericht automatisch erstellt',

    // Problem
    'problem.eyebrow': 'Das Problem',
    'problem.title': 'Öffentliche Programme versinken in Bürokratie.',
    'problem.desc': 'Manuelle Dokumentation in Sozialprogrammen führt zu Audit-Risiken und enormem Zeitverlust.',
    'problem.stat1Num': '40%',
    'problem.stat1Label': 'Verlorene Arbeitszeit',
    'problem.stat1Sub': 'durch manuelle Bürokratie — Öffentlicher Sektor Benchmark',
    'problem.stat2Num': 'Hoch',
    'problem.stat2Label': 'Audit- & Finanzrisiko',
    'problem.stat2Sub': 'Undokumentierte Ausgaben sind der Hauptgrund für Budgetkürzungen',
    'problem.stat3Num': 'Null',
    'problem.stat3Label': 'Echtzeit-Einblick',
    'problem.stat3Sub': 'Entscheidungsträger sehen Daten oft erst Wochen später',
    'problem.impact': '~$1 Bio. USD / Jahr',
    'problem.impactSub': 'Geschätztes globales Potenzial der Digitalisierung des öffentlichen Sektors — McKinsey',

    // Solution / How
    'how.eyebrow': 'Die Lösung',
    'how.title': 'Sprachbasierte & agentische KI-Compliance.',
    'how.desc': 'Keine komplexe Software-Schulung nötig. Mitarbeiter berichten über ihre gewohnten Kanäle.',
    'how.step1Num': '01',
    'how.step1Title': 'Sprechen statt Tippen',
    'how.step1Desc': 'Sprachnachricht via WhatsApp oder Telegram senden — barrierefrei.',
    'how.step2Num': '02',
    'how.step2Title': 'Agent strukturiert & prüft',
    'how.step2Desc': 'Unsere LangGraph-Engine validiert Daten in Echtzeit gegen Vorschriften.',
    'how.step3Num': '03',
    'how.step3Title': 'Automatische Berichte',
    'how.step3Desc': 'Jeder Bericht wird sofort prüfungssicher gespeichert.',

    // Modules
    'modules.eyebrow': 'Produktarchitektur',
    'modules.title': 'Eine Engine. Viele öffentliche Branchen.',
    'modules.desc': 'AI GovCoreX ist ein horizontales RegTech-OS für Behörden und öffentliche Träger.',
    'modules.m1Tag': 'AKTIV · FRÜHKINDLICHE BILDUNG',
    'modules.m1Title': 'KindiCore AI',
    'modules.m1Desc': 'Verwaltung von Kita-Netzwerken & frühkindlichen Programmen.',
    'modules.m2Tag': 'NÄCHSTE BRANCHE',
    'modules.m2Title': 'SocialCore AI',
    'modules.m2Desc': 'Sozialhilfe, Fördermittelverwaltung & Seniorenbetreuung.',
    'modules.m3Tag': 'ROADMAP',
    'modules.m3Title': 'HealthCore AI',
    'modules.m3Desc': 'Kommunale Gesundheitsteams & Ernährungsinitiativen.',

    // Traction
    'traction.eyebrow': 'Bewährte Ausführung',
    'traction.title': 'Vom Code zur staatlichen Nutzung in 5 Monaten.',
    'traction.desc': 'Validiert bei städtischen Trägern mit 100% Vertragsverlängerung.',
    'traction.t1Tag': 'PHASE 1',
    'traction.t1Title': 'Basis-System bereitgestellt',
    'traction.t1Sub': 'Agentische Kernarchitektur entwickelt.',
    'traction.t2Tag': 'PHASE 2',
    'traction.t2Title': 'Institutionelle Validierung',
    'traction.t2Sub': 'Im Einsatz bei städtischen Kita-Netzen.',
    'traction.t3Tag': 'ANKERKUNDE',
    'traction.t3Title': 'DASE Guayaquil',
    'traction.t3Sub': 'Vertrag im Jahresbudget verlängert.',
    'traction.t4Tag': 'EXPANSION',
    'traction.t4Title': 'MIES-Netzwerk',
    'traction.t4Sub': '11 weitere Zentren im Onboarding.',
    'traction.t5Tag': 'BINDUNG',
    'traction.t5Title': '100%',
    'traction.t5Sub': 'Jährliche Budgetverlängerungsrate.',

    // Moat
    'moat.eyebrow': 'Wettbewerbsvorteil',
    'moat.title': 'Sprachkomfort + behördliche Echtzeit-Compliance.',
    'moat.desc': 'Keine andere Plattform verbindet Sprachaufnahme mit automatischer Gesetztesprüfung.',
     me: 'Usabilität',
    'moat.q1': 'Klassische CRM- & Kita-Software',
    'moat.q2': 'AI GovCoreX (Agentisches Compliance-OS)',
    'moat.q3': 'Manuelle Papier-Bürokratie',
    'moat.q4': 'Veraltete Behörden-Systeme',
    'moat.axisY': 'SPRACHNUTZUNG & ZERO FRICTION →',
    'moat.axisX': 'ECHTZEIT COMPLIANCE →',
    'moat.m1Title': 'Proprietäre Compliance-Engine',
    'moat.m1Desc': 'Direkt an öffentliche Richtlinien und WHO-Standards angepasst.',
    'moat.m2Title': 'Hohe Wechselkosten',
    'moat.m2Desc': 'Tief in behördliche Prüfprozesse integriert.',
    'moat.m3Title': 'Sprach-Daten-Flywheel',
    'moat.m3Desc': 'Jede Audionachricht verbessert die Genauigkeit lokaler Dialekte.',

    // Footer / CTA
    'footer.ctaTitle': 'Bereit für die Zukunft der Verwaltung?',
    'footer.ctaDesc': 'Schließen Sie sich öffentlichen Trägern an, die auf transparente KI-Verwaltung setzen.',
    'footer.contact': 'Kontakt aufnehmen',
    'footer.rights': '© 2026 AI GovCoreX. Alle Rechte vorbehalten.',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Nutzungsbedingungen',

    // Beta Register
    'beta.header': 'Beta-Warteliste',
    'beta.subtitle': 'Bewerben Sie sich für exklusiven Zugang zur AI GovCoreX Beta.',
    'beta.step': 'Schritt {{current}} von {{total}}',
    'beta.prev': 'Zurück',
    'beta.next': 'Nächster Schritt',
    'beta.submit': 'VIP-Zugang anfordern',
    'beta.submitting': 'Wird gesendet...',
    'beta.completedBadge': 'Antrag eingegangen!',
    'beta.completedTitle': 'Sie sind auf der VIP-Warteliste!',
    'beta.completedSubtitle': 'Wir haben die Daten für {{company}} erhalten.',
    'beta.completedDesc': 'Unser Team prüft Ihre Angaben und sendet Ihnen die Zugangsdaten an {{email}}.',
    'beta.statusPending': 'Status: In Prüfung für Beta-Access',
    'beta.goToHome': 'Zurück zur Startseite',
    'beta.q1Title': 'Wie heißt Ihre Organisation oder Behörde?',
    'beta.q1Subtitle': 'Helfen Sie uns, Ihre Institution zuzuordnen.',
    'beta.q1Placeholder': 'z.B. Sozialamt / Kommunales Schulnetzwerk',
    'beta.q1Badge': 'Organisation',

    'beta.q2Title': 'In welchem öffentlichen Sektor sind Sie tätig?',
    'beta.q2Subtitle': 'Ermöglicht die Anpassung von Sprach- & Compliance-Modellen.',
    'beta.q2Badge': 'Sektor',
    'beta.q2Opt1': 'Frühkindliche Bildung & Kitas',
    'beta.q2Opt1Desc': 'Öffentliche Kitas und Kinderbetreuung',
    'beta.q2Opt2': 'Sozialhilfe & Förderung',
    'beta.q2Opt2Desc': 'Sozialprogramme, Seniorenhilfe',
    'beta.q2Opt3': 'Gesundheitswesen & Ernährung',
    'beta.q2Opt3Desc': 'Kommunale Gesundheitszentren & Ernährungsteams',
    'beta.q2Opt4': 'Schulverwaltung & Bildung',
    'beta.q2Opt4Desc': 'Schulbezirke und Schulverpflegung',
    'beta.q2Opt5': 'Kommunalverwaltung & Behörden',
    'beta.q2Opt5Desc': 'Stadtverwaltungen & Außendienst',
    'beta.q2Opt6': 'Sonstiger öffentlicher Sektor',
    'beta.q2Opt6Desc': 'Weitere Dienstleister oder Träger',

    'beta.q3Title': 'Wie viele Zentren oder Außendienstkräfte nutzen das System?',
    'beta.q3Subtitle': 'Hilft bei der Kapazitätsplanung.',
    'beta.q3Badge': 'Skalierung',
    'beta.q3Opt1': '1 bis 5 Zentren / Kräfte',
    'beta.q3Opt1Desc': 'Pilotprojekte oder kleine Netze',
    'beta.q3Opt2': '6 bis 20 Zentren / Kräfte',
    'beta.q3Opt2Desc': 'Wachsende kommunale Netze',
    'beta.q3Opt3': '21 bis 50 Zentren / Kräfte',
    'beta.q3Opt3Desc': 'Regionale Sozialprogramme',
    'beta.q3Opt4': 'Über 50 Zentren / Kräfte',
    'beta.q3Opt4Desc': 'Große Träger / Staatliche Netzwerke',

    'beta.q4Title': 'Welche Berichte & Abläufe möchten Sie automatisieren?',
    'beta.q4Subtitle': 'Beschreiben Sie Ihre täglichen Aufgaben.',
    'beta.q4Badge': 'Abläufe',
    'beta.q4Placeholder': 'z.B. Tägliche Anwesenheit, Essensausgabe, Entwicklungsberichte...',

    'beta.q5Title': 'Wie hoch ist Ihr aktueller Grad der KI-Nutzung?',
    'beta.q5Subtitle': 'Bestimmt Ihren digitalen Reifegrad.',
    'beta.q5Badge': 'Digitale Reife',
    'beta.q5Opt1': 'Einsteiger / Erste Schritte',
    'beta.q5Opt1Desc': 'Gelegentliche Nutzung von ChatGPT',
    'beta.q5Opt2': 'Fortgeschritten',
    'beta.q5Opt2Desc': 'Einfache Formulare oder Chatbots',
    'beta.q5Opt3': 'Experte',
    'beta.q5Opt3Desc': 'Suche nach autonomem KI-Betriebssystem',

    'beta.q6Title': 'Was ist Ihr Hauptziel mit AI GovCoreX?',
    'beta.q6Subtitle': 'Ihre Ziele leiten die Konfiguration.',
    'beta.q6Badge': 'Hauptziel',
    'beta.q6Placeholder': 'z.B. Papierlose Dokumentation, Echtzeit-Audits, WhatsApp-Sprachnotizen...',

    'beta.q7Title': 'Fast geschafft! Ihre Kontaktdaten',
    'beta.q7Subtitle': 'Wir senden Ihre Zugangsdaten an diese Adresse.',
    'beta.q7Badge': 'Letzter Schritt',
    'beta.q7Name': 'Vollständiger Name',
    'beta.q7NamePh': 'z.B. Markus Weber',
    'beta.q7Role': 'Offizielle Position',
    'beta.q7RolePh': 'z.B. Leiter der Verwaltung',
    'beta.q7Email': 'Offizielle E-Mail-Adresse',
    'beta.q7EmailPh': 'm.weber@behoerde.de',
    'beta.q7Phone': 'Telefon / WhatsApp',
    'beta.q7PhonePh': '+49 170 1234567',
    'beta.q7Security': 'Ihre Daten sind mit SSL verschlüsselt.',

    'beta.valText': 'Bitte füllen Sie dieses Feld aus.',
    'beta.valSelect': 'Bitte wählen Sie eine Option.',
    'beta.valContact': 'Bitte füllen Sie alle Kontaktfelder aus.',

    // Legal pages
    'legal.termsTitle': 'Nutzungsbedingungen',
    'legal.privacyTitle': 'Datenschutzerklärung und Datensicherheit',
    'legal.lastUpdated': 'Zuletzt aktualisiert: August 2026',
    'legal.backHome': 'Zurück zu AI GovCoreX',
    'legal.privacySec1Title': '1. Datenschutz und behördliche Compliance',
    'legal.privacySec1Text': 'AI GovCoreX nutzt mandantenfähige Datenbankisolation, SSL-Verschlüsselung und rollenbasierte Zugriffskontrollen (RBAC). Alle Compliance-Daten und Sprachberichte aus dem Außendienst werden in sicheren Cloud-Umgebungen gemäß behördlichen Datenschutzstandards gespeichert.',
    'legal.privacySec2Title': '2. Verwendung der erfassten Daten',
    'legal.privacySec2Text': 'Über die Beta-Warteliste übermittelte Daten werden ausschließlich zur Qualifizierung der Institution, Kapazitätsplanung und Bereitstellung der Zugangsdaten verwendet.',
    'legal.privacySec3Title': '3. Informationssicherheit',
    'legal.privacySec3Text': 'Wir setzen administrative und technische Schutzmaßnahmen ein, um unbefugten Zugriff, Offenlegung oder Manipulation öffentlicher Programmdaten zu verhindern.',
    'legal.termsSec1Title': '1. Plattformdienste und Governance',
    'legal.termsSec1Text': 'AI GovCoreX stellt ein autonomes Compliance-Betriebssystem für Behörden, Dienstleister und Träger von Sozialprogrammen bereit. Mit der Registrierung stimmen Organisationen den Compliance- und Datenschutzrichtlinien des öffentlichen Sektors zu.',
    'legal.termsSec2Title': '2. Sprachdaten und agentische Verarbeitung',
    'legal.termsSec2Text': 'Über offizielle Messaging-Kanäle (WhatsApp, Telegram) übermittelte Audioberichte werden mit Sprachmodellen verarbeitet, die strikt an die Richtlinien des jeweiligen Programms angepasst sind. Es erfolgt keine Weitergabe an unbefugte Dritte.',
    'legal.termsSec3Title': '3. Geistiges Eigentum und modulare Architektur',
    'legal.termsSec3Text': 'AI GovCoreX und seine vertikalen Module (einschließlich KindiCore AI, SocialCore AI und HealthCore AI) verbleiben im ausschließlichen geistigen Eigentum des Mutterunternehmens.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('aigovcorex_lang') as Language;
    if (saved && ['en', 'es', 'pt', 'fr', 'de'].includes(saved)) {
      setLanguageState(saved);
    } else {
      const browserLang = navigator.language.slice(0, 2).toLowerCase();
      if (['es', 'pt', 'fr', 'de'].includes(browserLang)) {
        setLanguageState(browserLang as Language);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aigovcorex_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
